### ISSUE TITLE
PR conflicts

### ISSUE THREAD

**Issue by dominikl** [ome/rOMERO-gateway#24]
Once OMERO 5.4.0 is out I definitely need the currently open PRs merged. There are several PRs depending on / building on top of each other or conflicting. I can hardly do anything with repository any longer.

Probably starting with the PRs without merge conflicts:
- #17 
- #18
- #21 

Then I can rebase/fix the others, like #22 to get the travis tests going (hopefully).

I'll also open a PR later to fix the version number, using an OMERO independent version.

/cc @jburel @joshmoore

**Comment by joshmoore** [comment]
Under the assumption that we'd like a first release (`0.x.0`) along with OMERO 5.4, :+1: for getting all those PRs in, conflicts resolved, and then the version number updated.

**Comment by sbesson** [comment]
With https://github.com/ome/rOMERO-gateway/milestone/2 and https://github.com/ome/rOMERO-gateway/releases/tag/v0.2.0, I assume we can close this @dominikl ?

**Comment by joshmoore** [comment]
Yup. I've done my mergin' :smile:
