### ISSUE TITLE
Review use of JDK before publishing images

### ISSUE THREAD

**Issue by joshmoore** [ome/rOMERO-gateway#30]
```
Saving to: ‘jdk-8u151-linux-x64.tar.gz’
```

The last time we looked into Java packaging, distributing a package version of the Oracle JDK was to be avoided. Since `install.R` is downloading the JDK, we should be careful with what happens with build docker images.

**Comment by dominikl** [comment]
I'm not quite sure where this is happening, maybe when the `rJava` dependency is installed? When I run `install.R` on a clean debian stretch it uses the installed openjdk version (although building on a clean debian needs some dependency solving, e. g. libcurl and libxml, maybe worth adding a note in README).

**Comment by joshmoore** [comment]
i.e. if we changed the base image we might be able to get rid of it?

**Comment by dominikl** [comment]
I would guess so, seems to be specific to the docker build. I'm not aware that the `romero.gateway` package has a explicit reference to the Oracle JDK any where.

**Comment by joshmoore** [comment]
Hmm.... ok. We'll need to look into what other R packages are doing on Docker Hub so that we're careful.

**Comment by dominikl** [comment]
Can be closed. Java installation is prerequisite, `install.R` doesn't download/install any JDK.
