### ISSUE TITLE
Use github "Release" to make compiled packages available

### ISSUE THREAD

**Issue by dominikl** [ome/rOMERO-gateway#47]
It is still difficult to install the romero.gateway package. The `install.R` script provides an automatic way to clone, build and install the package. But it also installs some packages with are actually only needed for the 'install.R' script (like `git2r`). And it makes use of some methods which are only available for R version >= 3.3, which can cause an issue with older OS, which only provide older R versions (@jburel  ran into this issue when setting up a docker build). All in all the `install.R` script is good for a developer for quickly building/testing different versions/branches, but it doesn't provide an easy way for an user to simply get the package.

Could we therefore use the Github "Release" feature? I. e. for each tag also create a release and attach the compiled binaries for Unix and Windows (CRAN provides a service to create a windows binary from source)? This would mean the user can simply download the package and install it with `install.packages('romero.gateway_x.y.z.tar.gz')` (or with RStudio).

(Only tested on my repository for now: https://github.com/dominikl/rOMERO-gateway/releases/tag/0.3.0 )

**Comment by jburel** [comment]
The problem does not happen with the current dockerfile in this repo since it is based on debian:unstable so version 3.5 is actually installed
on Ubuntu, installing ``r-base`` will install version ``3.2``

**Comment by dominikl** [comment]
https://github.com/ome/rOMERO-gateway/pull/62
