### ISSUE TITLE
User Requirements and Scoping of R Integration

### ISSUE THREAD

**Issue by gusferguson** [ome/rOMERO-gateway#5]
**User Requirements for R Integration**

R website: https://www.r-project.org

Petr, Dominik, Gus - Meeting 15-12-10 with:

Paul Andrews & John Raynor
National Phenotypic Screening Centre (NPSC)

Just starting out on project which will be using R with.

Bioconductor probably most popular package - has >1000 R-based modules
https://www.bioconductor.org

Phenotypic screening
- aim is to discriminate between phenotypes and the effects of chemicals
- basically want to create fingerprints of cells of interest
- associate these with metadata
- do statistical analysis of occurrence vs conditions/treatments/etc.

Actual image data not really what they run R on - more often it is the metadata generated from the image data - e.g. number of cells of each phenotype, associated treatments, genome data

Multi parametric analysis is where it all gets messy
Use Principal Component Analysis (PCA)

Asked about running R on the server and parallelisation.
- nothing stopping it
- Dom: server-side probably work well with R 

In early stages of an experiment workflow would be:
- run script on data
- In ImageJ
- visually inspect results e.g. have the cells been identified correctly
- may make adjustments
- may use overlays to compare ROIs
- save all work back to OMERO

Need/would like:
     - need way of viewing tabular data (in spreadsheet format)
     - would like to be able to view statistics related to context alongside viewing the data.
     - would be good to be able to link bench data from e-lab book to data - e.g. experimental conditions, description of reagents etc. - these details would be essential for other scientists to be able to work with the data
     - need to be able to add further metadata - e.g. the results of analysis - to data after upload

Shown:
- ImageJ-OMERO and Matlab-OMERO integration - these are more or less how they would see R working.
- IDR - issues with how metadata is displayed - would need spreadsheet view 

Some key papers that explain common processes:

Phenotypic screening of the ToxCast chemical library to classify toxic and therapeutic mechanisms. Kleinstreuer et al. Nature Biotechnology 32, 583–591(2014) doi:10.1038/nbt.2914
http://www.nature.com/nbt/journal/v32/n6/full/nbt.2914.html

Going forward:
Paul will:
- put together a schematic of their workflow and how R fits into it.
- send references for some more key papers
- happy to work more with us on this

Anne Carpenter - Broad Institute - collaborates with
Neil Carragher - Edinburgh - http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4035564/

BTW - this is up and coming:
Image-based chemical screening
http://www.nature.com/nchembio/journal/v3/n8/full/nchembio.2007.15.html

and:

Pieta Schofield
Barton Group

Two image processing libraries popular in biology:
EBImage https://www.bioconductor.org/packages/3.3/bioc/html/EBImage.html
- processing images, segmentation
- imager http://dahtah.github.io/imager/
- uses C image libraries
- has own internal data structure
- pixel data is held in grid structure
- some pixel —> grid conversion in the package

R slow for image processing - Matlab faster

Important:
- R data structures are crucial to functionality
- functions are overloaded and what they give depends on theta structure
- standard data format is grid e.g. RNA seek analysis - fragment counts vs, genes
- 2D grid holds data
- another 2D grid describes the data structure
- another 2D grid describes the data

R expects to receive data as lists - e.g.:
- element 1 is data
- element 2 is data about columns
- element 3 is data about rows

R only object-orientated to a certain extent.

Format of R output:
1.   own internal binary dumps of memory as R data file
   - i.e. way of saving data to drive
   - libraries to output in other formats e.g. JSON, CSV
   - if storing R files probably best to use JSON
   - e.g. Pieta’s FLIM-FRET work, gave back grid which was essentially another image, each cell a pixel
2.   Metadata type of output
   - e.g. grid that contains scores for treatment
   - returns static calculation across images

If HSC output is in CSV need to get it into correct structure to be able to run R functions against it.

Gus: Looks as if image processing using one/both of the above mentioned libraries may be a good place to start

Should be able to use R to do stats on segmentations or ROIs drawn/done by other apps.

Rob Kent in Angus Lamonds group is developer of DataShop
- would certainly be worth picking his brains
- PEP tracker for mass spectroscopy
- imports data and runs R scripts against it
- saves back to mass spec apps
- has GUIs to see plots and runs etc.

Key point will be getting stuff into the correct R data structures so the functions perform correctly

**Comment by davidmam** [comment]
I've put the imaging libraries referenced (imager, EBImage) onto the standard Uni desktop R install.

**Comment by jburel** [comment]
We now have example noteboosk using EBImage

**Comment by dominikl** [comment]
I think this can be closed now. We have an example using EBImage now. I guess further examples / use cases will be discussed on the respective IDR / training notebooks repositories.
