### ISSUE TITLE
Packaging the ROMERO interface

### ISSUE THREAD

**Issue by davidmam** [ome/rOMERO-gateway#6]
There is a sort of specification for including the jar files from external sources. They should be under exec/java instead of lib. This requires a simple change in the Java integration classpath.
The jar files can then be included in the package so it is known to work against a given OMERO release and be a one-click install.

**Comment by dominikl** [comment]
Can be closed. The package now matches the general R package specification. Thanks David. I changed the structure accordingly, but never got back to reply to or close this issue.
