### ISSUE TITLE
installation issue in Rstudio

### ISSUE THREAD

**Issue by alex-rapp** [ome/rOMERO-gateway#65]
when I try to install rOMERO either with the downloaded tar.gz or with the install.package("") command I get an error stating:
Warning in install.packages :
  installation of package ‘/var/folders/8h/yqhr7vgs3333f2wt3x2082j80000gn/T//RtmpVr1rWw/downloaded_packages/romero.gateway_0.4.4.tar.gz’ had non-zero exit status

I have rJava installed on the system. The system is Macos 10.12, R studio is 1.1.463 and R is version 3.5.

Any suggestions?
Thanks Alex

**Comment by alex-rapp** [comment]
Hi again,
I identified the problem. In the error code I found:
error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib

So the rJava is pointing to the jdk-11 installation, which I do not have. After installing jdk-11 I was able to install rOMERO-gateway. 
I am using jdk-12 and the Java path variables are set correctly.
Best wishes
Alex

**Comment by dominikl** [comment]
Thanks Alex. rJava can be a bit tricky. Often a `R CMD javareconf` as root fixes these kind of issues  too. Just a heads-up: We're currently preparing a 0.4.5 release, you will probably need that if you upgrade R to current version 3.6.
