### ISSUE TITLE
Installation problem on Win10 platform -  error: cannot add binding of 'Collection' to the base environment

### ISSUE THREAD

**Issue by c5creative** [ome/rOMERO-gateway#94]
Greetings!

Running into some problems getting this installed in Win10, within R4.1 env. I'm hoping the following is sufficient to describe the problem, and that someone may have suggestions on how to get this to work. Thank you.

1. Installed the recommended `Adopt OpenJDK 11`. Env/paths seems good:
![image](https://user-images.githubusercontent.com/5258731/132861482-d1c15e93-d0db-4923-ad7b-20270886b148.png)

2. Installed `rOMERO-gateway`, without issue:
    ```
    > install.packages("https://github.com/ome/rOMERO-gateway/releases/download/v0.4.10/romero.gateway_0.4.10.zip", repos = NULL)
    Installing package into ‘C:/Users/cartaij/R/win-library/4.1’
    (as ‘lib’ is unspecified)
    trying URL 'https://github.com/ome/rOMERO-gateway/releases/download/v0.4.10/romero.gateway_0.4.10.zip'
    Content type 'application/octet-stream' length 251494 bytes (245 KB)
    downloaded 245 KB
    
    package ‘romero.gateway’ successfully unpacked and MD5 sums checked
    ```

3. When loading package, error emerges:
    ```
    > library(romero.gateway)
    Loading required package: rJava
    Loading required package: jpeg
    Loading required package: httr
    Have to download OMERO Java libraries from downloads.openmicroscopy.org.
    Proceed? [y/n]
    y
    Downloading https://downloads.openmicroscopy.org/latest/omero5.6/OMERO.java.zip ...
    Extracting...
    Finished. OMERO Java libraries saved in C:/Users/cartaij/R/win-library/4.1/romero.gateway/java
    Error: package or namespace load failed for ‘romero.gateway’:
     .onAttach failed in attachNamespace() for 'romero.gateway', details:
      call: env$Collection <- J("java.util.Collection")
      error: cannot add binding of 'Collection' to the base environment
    ```

**Comment by dominikl** [comment]
Thanks for reporting this issue. I'll have a look into it. I've not tested the R gateway with the latest version of R (or latest rJava), maybe something's changed there.

**Comment by c5creative** [comment]
Thanks, appreciate it! Perhaps related to a R 4.1.0 change where the "the base environment and its namespace are now locked , so one can no longer add bindings to these or remove from these".
* https://stat.ethz.ch/pipermail/r-devel/2021-May/080761.html
* https://stackoverflow.com/a/68823803
